from __future__ import annotations

from copy import deepcopy
from datetime import datetime, timezone
from uuid import uuid4

DATA_CLASS = "SIMULATED"


def now() -> str:
    return datetime.now(timezone.utc).isoformat()


BASE_STATE = {
    "stage": "intake",
    "decision": None,
    "handoff": None,
    "scale_consents": {},
    "users": [
        {
            "id": "usr-officer",
            "name": "Ananya Deshmukh",
            "email": "officer@praman.local",
            "password": "demo123",
            "role": "officer",
            "mfa": "123456",
            "department": "Urban Development / PWD",
            "data_class": DATA_CLASS,
        },
        {"id": "usr-evaluator", "name": "Pilot Evaluator", "email": "evaluator@praman.local", "password": "demo123", "role": "evaluator", "mfa": "123456", "data_class": DATA_CLASS},
        {"id": "usr-startup", "name": "SkylineAI Portal", "email": "startup@praman.local", "password": "demo123", "role": "startup", "mfa": "123456", "data_class": DATA_CLASS},
        {"id": "usr-admin", "name": "MSInS Admin", "email": "admin@praman.local", "password": "demo123", "role": "msins_admin", "mfa": "123456", "data_class": DATA_CLASS},
        {"id": "usr-auditor", "name": "Audit Officer", "email": "auditor@praman.local", "password": "demo123", "role": "auditor", "mfa": "123456", "data_class": DATA_CLASS},
        {"id": "usr-ciso", "name": "Security Reviewer", "email": "ciso@praman.local", "password": "demo123", "role": "ciso", "mfa": "123456", "data_class": DATA_CLASS},
    ],
    "departments": [
        {"id": "dept-pune", "name": "Urban Development / PWD", "location": "Pune", "data_class": DATA_CLASS},
        {"id": "dept-mumbai", "name": "Mumbai Urban Development", "location": "Mumbai", "data_class": DATA_CLASS},
        {"id": "dept-nashik", "name": "Nashik Municipal", "location": "Nashik", "data_class": DATA_CLASS},
        {"id": "dept-nagpur", "name": "Nagpur PWD", "location": "Nagpur", "data_class": DATA_CLASS},
    ],
    "problems": [
        {
            "id": "1042",
            "display_id": "#1042",
            "department": "Urban Development / PWD",
            "location": "Pune Municipal Bus Fleet",
            "title": "AI Road Damage Detection for Public Transport Routes",
            "narrative": "Need an AI-powered solution to detect road damage using public transport. The department needs road-condition insights from municipal bus routes, geotagged alerts for field teams, and reliable operation in varying lighting conditions. The pilot must be completed within 90 days and remain within the approved innovation budget.",
            "budget": "₹50L – ₹1Cr",
            "timeline_days": 90,
            "core_kpi": "Road-damage detection recall ≥ 90%",
            "constraint": "Night-time false positives",
            "domain": "Urban Infrastructure",
            "technology": "Computer Vision",
            "supporting": ["GPS", "Geospatial Analytics", "Edge / On-device inference"],
            "deployment": "Municipal bus fleet + field inspection workflow",
            "security": "Security questionnaire + deployment review required.",
            "status": "Draft",
            "data_class": DATA_CLASS,
        }
    ],
    "requirements": {},
    "startups": [
        {
            "id": "startup-skyline",
            "name": "SkylineAI Solutions",
            "dpiit": "SIMULATED VERIFIED",
            "capabilities": ["Computer Vision", "GPS", "Edge deployment", "Geospatial outputs", "ITS pilot evidence"],
            "location_readiness": ["Pune", "Maharashtra"],
            "budget_band": "₹50L – ₹1Cr",
            "eligibility": "PASS",
            "score": 93,
            "data_class": DATA_CLASS,
        },
        {"id": "startup-aeroscan", "name": "AeroScan Tech", "dpiit": "SIMULATED VERIFIED", "capabilities": ["Drone analytics", "Geospatial capability"], "eligibility": "PASS", "score": 87, "data_class": DATA_CLASS},
        {"id": "startup-urbansentry", "name": "UrbanSentry", "dpiit": "SIMULATED VERIFIED", "capabilities": ["Road monitoring", "Municipal workflow"], "eligibility": "PASS", "score": 82, "data_class": DATA_CLASS},
    ],
    "recommendations": [],
    "pilots": {},
    "evidence": [],
    "audit": [],
    # ── NEW: Implementation Intelligence ──────────────────────────────────────
    "implementation": {
        "id": "impl-1042",
        "project_id": "1042",
        "name": "AI Road Damage Detection — Smart Road Monitoring",
        "startup": "SkylineAI Solutions",
        "department": "Urban Development / PWD",
        "stage": "In Progress",
        "blocker_resolved": False,
        "tasks": [
            {
                "id": "task-01",
                "name": "Prepare Road Survey Data",
                "description": "Collect baseline road condition data from PWD archives and current municipal bus GPS logs. Prepare dataset for model training validation.",
                "owner": "Dept. Engineer",
                "department": "Urban Development / PWD",
                "start_date": "2026-10-01",
                "deadline": "2026-10-10",
                "status": "Completed",
                "priority": "High",
                "completion_pct": 100,
                "depends_on": [],
                "risk": "Low — historical data available",
                "evidence": "EVID-2028-101",
                "notes": "Completed on schedule. 14,000 km of route data prepared.",
                "data_class": DATA_CLASS,
            },
            {
                "id": "task-02",
                "name": "Government API Integration",
                "description": "IT Department to expose municipal data APIs for SkylineAI platform to consume. Includes authentication, rate limiting, and data format alignment.",
                "owner": "IT Lead",
                "department": "IT Department",
                "start_date": "2026-10-08",
                "deadline": "2026-10-15",
                "status": "Blocked",
                "priority": "Critical",
                "completion_pct": 30,
                "depends_on": ["task-01"],
                "risk": "CRITICAL — All downstream tasks blocked until API is ready",
                "evidence": "EVID-2028-102",
                "notes": "API authentication spec under internal review. Delayed 10 days. This is the PRIMARY BLOCKER for the entire implementation.",
                "data_class": DATA_CLASS,
            },
            {
                "id": "task-03",
                "name": "Deploy SkylineAI Platform",
                "description": "Install and configure the SkylineAI road damage detection platform on municipal bus fleet cameras and backend infrastructure.",
                "owner": "CTO",
                "department": "SkylineAI Solutions",
                "start_date": "2026-10-16",
                "deadline": "2026-10-25",
                "status": "Blocked",
                "priority": "High",
                "completion_pct": 0,
                "depends_on": ["task-02"],
                "risk": "HIGH — Cannot deploy without Government API access",
                "evidence": "",
                "notes": "Blocked pending task-02 (Government API Integration). Startup is ready.",
                "data_class": DATA_CLASS,
            },
            {
                "id": "task-04",
                "name": "Field Testing",
                "description": "Independent evaluator conducts field trials on 5 bus routes, verifying detection accuracy, false positive rate, and system reliability under real conditions.",
                "owner": "Pilot Evaluator",
                "department": "Independent Evaluation",
                "start_date": "2026-10-26",
                "deadline": "2026-10-30",
                "status": "Blocked",
                "priority": "High",
                "completion_pct": 0,
                "depends_on": ["task-03"],
                "risk": "HIGH — Cannot commence without platform deployment",
                "evidence": "",
                "notes": "Blocked pending task-03 (Deploy Platform).",
                "data_class": DATA_CLASS,
            },
            {
                "id": "task-05",
                "name": "Final Acceptance",
                "description": "Government officer reviews field testing results, signs off on performance against SLA targets, and formally accepts the solution for production operation.",
                "owner": "Ananya Deshmukh",
                "department": "Urban Development / PWD",
                "start_date": "2026-11-01",
                "deadline": "2026-11-05",
                "status": "Not Started",
                "priority": "Critical",
                "completion_pct": 0,
                "depends_on": ["task-04"],
                "risk": "MEDIUM — Dependent on field testing results",
                "evidence": "",
                "notes": "Acceptance criteria: detection recall ≥ 90%, uptime ≥ 95%, false positive rate ≤ 5%.",
                "data_class": DATA_CLASS,
            },
        ],
        "data_class": DATA_CLASS,
    },
    # ── NEW: Responsibility Matrix ─────────────────────────────────────────────
    "responsibilities": [
        {"id": "resp-01", "activity": "Problem Requirement Definition", "responsible_role": "Government Officer", "responsible_name": "Ananya Deshmukh", "department": "Urban Development / PWD", "deadline": "2026-09-20", "status": "Completed", "blocked_by": None, "notes": "Requirement approved.", "data_class": DATA_CLASS},
        {"id": "resp-02", "activity": "Startup Evaluation", "responsible_role": "Pilot Evaluator", "responsible_name": "Pilot Evaluator", "department": "Independent Evaluation", "deadline": "2026-09-30", "status": "Completed", "blocked_by": None, "notes": "3 startups evaluated and ranked.", "data_class": DATA_CLASS},
        {"id": "resp-03", "activity": "Evidence Validation", "responsible_role": "Independent Expert", "responsible_name": "Pilot Evaluator", "department": "Independent Evaluation", "deadline": "2026-10-05", "status": "Completed", "blocked_by": None, "notes": "5 evidence documents reviewed.", "data_class": DATA_CLASS},
        {"id": "resp-04", "activity": "Security Review", "responsible_role": "CISO", "responsible_name": "Security Reviewer", "department": "IT Security", "deadline": "2026-10-10", "status": "In Progress", "blocked_by": None, "notes": "80% complete. Pending final sign-off.", "data_class": DATA_CLASS},
        {"id": "resp-05", "activity": "Pilot Execution", "responsible_role": "Startup", "responsible_name": "SkylineAI CTO", "department": "SkylineAI Solutions", "deadline": "2026-10-25", "status": "Blocked", "blocked_by": "Government API Integration (task-02)", "notes": "Platform deployment blocked by IT Department.", "data_class": DATA_CLASS},
        {"id": "resp-06", "activity": "API Integration", "responsible_role": "IT Lead", "responsible_name": "IT Lead", "department": "IT Department", "deadline": "2026-10-15", "status": "Blocked", "blocked_by": "API authentication spec under review", "notes": "PRIMARY BLOCKER. Delays all downstream tasks.", "data_class": DATA_CLASS},
        {"id": "resp-07", "activity": "Field Deployment", "responsible_role": "Startup + Department", "responsible_name": "SkylineAI + PWD Field Team", "department": "SkylineAI / PWD", "deadline": "2026-10-30", "status": "Blocked", "blocked_by": "Government API Integration (task-02)", "notes": "Awaiting platform deployment.", "data_class": DATA_CLASS},
        {"id": "resp-08", "activity": "Final Acceptance", "responsible_role": "Government Officer", "responsible_name": "Ananya Deshmukh", "department": "Urban Development / PWD", "deadline": "2026-11-05", "status": "Not Started", "blocked_by": None, "notes": "Acceptance gate pending field testing completion.", "data_class": DATA_CLASS},
        {"id": "resp-09", "activity": "Audit & Compliance", "responsible_role": "Auditor", "responsible_name": "Audit Officer", "department": "Audit Office", "deadline": "2026-11-10", "status": "In Progress", "blocked_by": None, "notes": "Append-only audit log maintained throughout.", "data_class": DATA_CLASS},
    ],
    # ── NEW: Monitoring Records ────────────────────────────────────────────────
    "monitoring": [
        {
            "id": "mon-01",
            "month": "Month 1",
            "period": "Nov 2026",
            "accuracy_pct": 89,
            "uptime_pct": 96,
            "cost_lakh": 2.1,
            "issues_count": 4,
            "kpis": [
                {"name": "Detection Recall", "promised": "≥ 90%", "actual": "89%", "unit": "%", "variance": "-1%", "met": False},
                {"name": "Uptime", "promised": "≥ 95%", "actual": "96%", "unit": "%", "variance": "+1%", "met": True},
                {"name": "Cost / Month", "promised": "≤ ₹2.5L", "actual": "₹2.1L", "unit": "Lakh", "variance": "-₹0.4L", "met": True},
                {"name": "False Positive Rate", "promised": "≤ 5%", "actual": "6.2%", "unit": "%", "variance": "+1.2%", "met": False},
            ],
            "notes": "Detection recall slightly below target. Night-time false positives reported. Model calibration in progress.",
            "evidence_ref": "EVID-MON-2026-11",
            "data_class": DATA_CLASS,
        },
        {
            "id": "mon-02",
            "month": "Month 2",
            "period": "Dec 2026",
            "accuracy_pct": 91,
            "uptime_pct": 97,
            "cost_lakh": 1.8,
            "issues_count": 2,
            "kpis": [
                {"name": "Detection Recall", "promised": "≥ 90%", "actual": "91%", "unit": "%", "variance": "+1%", "met": True},
                {"name": "Uptime", "promised": "≥ 95%", "actual": "97%", "unit": "%", "variance": "+2%", "met": True},
                {"name": "Cost / Month", "promised": "≤ ₹2.5L", "actual": "₹1.8L", "unit": "Lakh", "variance": "-₹0.7L", "met": True},
                {"name": "False Positive Rate", "promised": "≤ 5%", "actual": "4.8%", "unit": "%", "variance": "-0.2%", "met": True},
            ],
            "notes": "Night-time model update resolved false positive issue. All KPIs on track.",
            "evidence_ref": "EVID-MON-2026-12",
            "data_class": DATA_CLASS,
        },
        {
            "id": "mon-03",
            "month": "Month 3",
            "period": "Jan 2027",
            "accuracy_pct": 93,
            "uptime_pct": 99,
            "cost_lakh": 1.6,
            "issues_count": 0,
            "kpis": [
                {"name": "Detection Recall", "promised": "≥ 90%", "actual": "93%", "unit": "%", "variance": "+3%", "met": True},
                {"name": "Uptime", "promised": "≥ 95%", "actual": "99%", "unit": "%", "variance": "+4%", "met": True},
                {"name": "Cost / Month", "promised": "≤ ₹2.5L", "actual": "₹1.6L", "unit": "Lakh", "variance": "-₹0.9L", "met": True},
                {"name": "False Positive Rate", "promised": "≤ 5%", "actual": "2.1%", "unit": "%", "variance": "-2.9%", "met": True},
            ],
            "notes": "Excellent performance across all KPIs. Zero issues reported. System operating beyond SLA commitments.",
            "evidence_ref": "EVID-MON-2027-01",
            "data_class": DATA_CLASS,
        },
    ],
    # ── NEW: Project Outcome ───────────────────────────────────────────────────
    "outcome": {
        "id": "outcome-1042",
        "project_id": "1042",
        "result": "Successful",
        "reason": "Solution exceeded all KPI targets after an initial API integration delay in Month 1. Month 3 performance of 93% detection recall, 99% uptime, and ₹1.6L/month cost demonstrates strong ROI and reliability.",
        "related_evidence": "EVID-2028-102, EVID-MON-2027-01",
        "related_dependency": "Government API Integration (task-02) caused 2-week deployment delay",
        "completion_date": "2027-01-31",
        "actual_duration_days": 122,
        "dimensions": [
            {"name": "Technical Performance", "expected": "90% recall", "actual": "93% recall", "variance": "+3%", "result": "Exceeded Target"},
            {"name": "Financial Outcome", "expected": "≤ ₹2.5L/month", "actual": "₹1.6L/month avg", "variance": "-36%", "result": "Exceeded Target"},
            {"name": "Operational Reliability", "expected": "≥ 95% uptime", "actual": "97.3% avg uptime", "variance": "+2.3%", "result": "Exceeded Target"},
            {"name": "Citizen Impact", "expected": "20% faster pothole detection", "actual": "27% faster detection", "variance": "+7%", "result": "Exceeded Target"},
            {"name": "Implementation Time", "expected": "90 days", "actual": "122 days", "variance": "+32 days", "result": "Partially Met"},
            {"name": "Field Adoption", "expected": "80% field team adoption", "actual": "88% adoption", "variance": "+8%", "result": "Exceeded Target"},
        ],
        "data_class": DATA_CLASS,
    },
    # ── NEW: Lessons Learned ──────────────────────────────────────────────────
    "lessons": [
        {
            "id": "lesson-01",
            "project_id": "1042",
            "category": "Integration",
            "lesson": "Government API dependency caused a 2-week deployment delay. The IT Department API authentication spec was not finalized before implementation start.",
            "what_worked": "Road survey data preparation completed on schedule. Startup platform was ready to deploy when API access was finally granted.",
            "what_failed": "API integration dependency was not identified as critical-path risk during procurement. No escalation process existed.",
            "delay_cause": "Government API authentication specification delayed by 10 days due to internal review process.",
            "dependency_issue": "Government API Integration (task-02) blocked Startup Deployment, Field Testing, and Final Acceptance.",
            "recommendation": "Perform a Government API readiness assessment before implementation start. Confirm API specifications are finalized and test environment access is available. Add API readiness as a procurement prerequisite.",
            "reuse_recommended": True,
            "startup_recommended": True,
            "evidence_ref": "EVID-2028-102",
            "outcome_ref": "outcome-1042",
            "risk_ref": "Integration Risk",
            "data_class": DATA_CLASS,
        },
        {
            "id": "lesson-02",
            "project_id": "1042",
            "category": "Technical",
            "lesson": "Night-time false positive rate exceeded 5% in Month 1 due to insufficient night-time training data in the pilot phase. This was resolved by a model update in Month 2.",
            "what_worked": "The startup responded quickly with a targeted model calibration update. Field team feedback was instrumental in identifying the night-time issue.",
            "what_failed": "Pilot evaluation did not include sufficient night-time test scenarios. KPI targets were set without a night-time specific baseline.",
            "delay_cause": "Model calibration required 3 weeks of additional data collection.",
            "dependency_issue": "None — resolved within startup's scope.",
            "recommendation": "Include night-time and adverse-lighting scenarios explicitly in pilot KPI targets. Require 30% of pilot evaluation hours to be conducted in low-light conditions.",
            "reuse_recommended": True,
            "startup_recommended": True,
            "evidence_ref": "EVID-MON-2026-11",
            "outcome_ref": "outcome-1042",
            "risk_ref": "Technical Risk",
            "data_class": DATA_CLASS,
        },
        {
            "id": "lesson-03",
            "project_id": "1042",
            "category": "Operational",
            "lesson": "Field adoption exceeded targets (88% vs 80% expected) because the startup invested in a dedicated onboarding session for field supervisors before deployment.",
            "what_worked": "Startup-led field team training program. Weekly check-ins with field supervisors in Month 1. Simple mobile interface reduced training time.",
            "what_failed": "Initial onboarding plan did not allocate sufficient time. Was added reactively after Month 1 feedback.",
            "delay_cause": "No delay — resolved proactively.",
            "dependency_issue": "None.",
            "recommendation": "Include mandatory field team onboarding and training plan as a standard requirement in all future AI deployment procurement. Budget 5 working days for onboarding before go-live.",
            "reuse_recommended": True,
            "startup_recommended": True,
            "evidence_ref": "EVID-MON-2027-01",
            "outcome_ref": "outcome-1042",
            "risk_ref": "Operational Risk",
            "data_class": DATA_CLASS,
        },
    ],
    # ── NEW: Institutional Memory ──────────────────────────────────────────────
    "institutional_memory": [
        {
            "id": "mem-pune-2026",
            "year": 2026,
            "city": "Pune",
            "department": "Urban Development / PWD",
            "problem": "AI Road Damage Detection for Public Transport Routes",
            "domain": "Urban Infrastructure",
            "technology": "Computer Vision",
            "startup": "SkylineAI Solutions",
            "startup_id": "startup-skyline",
            "outcome": "Successful",
            "actual_accuracy_pct": 93,
            "actual_cost_lakh": 1.6,
            "implementation_days": 122,
            "pilot_score": 91,
            "what_worked": [
                "Computer vision model performed well on daylight routes",
                "Geospatial alert system integrated with field inspection workflow",
                "Startup was responsive to feedback and resolved night-time issue quickly",
                "Edge deployment on bus cameras worked reliably",
            ],
            "what_failed": [
                "Government API integration caused 2-week delay",
                "Night-time false positives exceeded target in Month 1",
                "API authentication spec was not finalized at implementation start",
            ],
            "known_dependencies": [
                "Government Data API (IT Department)",
                "Municipal Bus Camera Infrastructure (PWD)",
                "GPS Integration (Bus Fleet Management)",
            ],
            "known_risks": [
                "API integration dependency — ensure IT Department readiness before implementation",
                "Night-time performance — require low-light pilot testing",
                "Field adoption — plan dedicated onboarding program",
            ],
            "lessons": [
                "Perform Government API readiness assessment before implementation start",
                "Include night-time scenarios in pilot KPI targets",
                "Budget field team onboarding as a mandatory deliverable",
            ],
            "failure_causes": [],
            "similarity_signature": ["urban infrastructure", "road monitoring", "computer vision", "municipal transport", "GPS geospatial"],
            "data_class": DATA_CLASS,
        },
        {
            "id": "mem-nashik-2025",
            "year": 2025,
            "city": "Nashik",
            "department": "Nashik Municipal Corporation",
            "problem": "Road Condition Monitoring Using Drone Analytics",
            "domain": "Urban Infrastructure",
            "technology": "Drone Analytics",
            "startup": "AeroScan Tech",
            "startup_id": "startup-aeroscan",
            "outcome": "Partially Successful",
            "actual_accuracy_pct": 84,
            "actual_cost_lakh": 3.2,
            "implementation_days": 138,
            "pilot_score": 79,
            "what_worked": [
                "Drone survey coverage was comprehensive",
                "Geospatial outputs integrated with GIS system",
                "Startup delivered all contractual documentation",
            ],
            "what_failed": [
                "API integration with municipal GIS delayed by 3 weeks",
                "Drone operation requires special permits — not budgeted",
                "Weather dependency reduced operational days by 22%",
                "Night-time capability was absent — only daytime operation",
            ],
            "known_dependencies": [
                "Municipal GIS API",
                "DGCA drone operating permits",
                "Weather conditions",
            ],
            "known_risks": [
                "Drone permit dependency — verify DGCA clearance at procurement stage",
                "Weather operational risk — budget for weather downtime",
                "API integration risk — same as Pune project",
            ],
            "lessons": [
                "Verify all regulatory permits before procurement award",
                "Government API readiness is a recurring critical risk — assess early",
                "Drone-based solutions require explicit weather contingency planning",
            ],
            "failure_causes": [
                "API integration delayed by 3 weeks",
                "Drone permit delays caused 2-week operational gap",
            ],
            "similarity_signature": ["urban infrastructure", "road monitoring", "geospatial", "municipal"],
            "data_class": DATA_CLASS,
        },
        {
            "id": "mem-nagpur-2024",
            "year": 2024,
            "city": "Nagpur",
            "department": "Nagpur PWD",
            "problem": "Smart Road Monitoring System Using IoT Sensors",
            "domain": "Urban Infrastructure",
            "technology": "IoT Sensors",
            "startup": "UrbanSentry",
            "startup_id": "startup-urbansentry",
            "outcome": "Failed",
            "actual_accuracy_pct": 62,
            "actual_cost_lakh": 5.8,
            "implementation_days": 180,
            "pilot_score": 58,
            "what_worked": [
                "Sensor hardware installation was completed on schedule",
                "Basic vibration data collection functional",
            ],
            "what_failed": [
                "Government API integration failed completely — incompatible data formats",
                "High maintenance cost — sensors required monthly calibration",
                "Low field adoption — field teams did not use the alerts",
                "Detection accuracy remained at 62% — below 80% minimum threshold",
                "No escalation process for dependency failures",
            ],
            "known_dependencies": [
                "Government Road Database API (incompatible format)",
                "Sensor hardware maintenance contracts",
                "Field team training and adoption",
            ],
            "known_risks": [
                "API format compatibility — must validate before procurement",
                "High ongoing maintenance cost for sensor networks",
                "Field adoption risk — IoT sensors require significant training",
                "Detection accuracy risk — IoT vibration data alone insufficient for road damage classification",
            ],
            "lessons": [
                "Validate API format compatibility before procurement award — not just availability",
                "Include maintenance cost projections in total cost of ownership",
                "Require field adoption rate as a mandatory pilot KPI",
                "Verify detection accuracy baseline during proof-of-concept before pilot",
            ],
            "failure_causes": [
                "API integration failure — incompatible data formats",
                "High maintenance cost exceeded budget by 132%",
                "Field adoption remained below 20% — system not used",
                "Detection accuracy never reached minimum threshold",
            ],
            "similarity_signature": ["urban infrastructure", "road monitoring", "iot", "municipal", "sensor"],
            "data_class": DATA_CLASS,
        },
    ],
    # ── NEW: Risk Radar ────────────────────────────────────────────────────────
    "risk_radar": [
        {"category": "Technical Risk", "score_pct": 18, "level": "Low", "reason": "SkylineAI's computer vision model is validated. Month 1 night-time issue resolved in Month 2. Current detection recall at 93%.", "linked_task": None, "linked_dependency": None, "data_class": DATA_CLASS},
        {"category": "Financial Risk", "score_pct": 12, "level": "Low", "reason": "Actual cost at ₹1.6L/month is 36% below committed ceiling of ₹2.5L/month. Strong financial performance.", "linked_task": None, "linked_dependency": None, "data_class": DATA_CLASS},
        {"category": "Implementation Risk", "score_pct": 67, "level": "High", "reason": "Government API Integration (task-02) is blocked. 3 downstream tasks (Deploy Platform, Field Testing, Acceptance) are blocked, causing 2-week schedule overrun.", "linked_task": "task-02", "linked_dependency": "Government API", "data_class": DATA_CLASS},
        {"category": "Integration Risk", "score_pct": 71, "level": "High", "reason": "Government API authentication spec is under internal review. IT Department has not provided API access. This is the primary blocker with cascade to 3 tasks.", "linked_task": "task-02", "linked_dependency": "Government API Integration", "data_class": DATA_CLASS},
        {"category": "Cybersecurity Risk", "score_pct": 24, "level": "Medium", "reason": "Security assessment is 80% complete. Outstanding items include penetration testing and data residency confirmation. CISO review pending.", "linked_task": None, "linked_dependency": None, "data_class": DATA_CLASS},
        {"category": "Vendor Risk", "score_pct": 9, "level": "Low", "reason": "SkylineAI has demonstrated responsiveness and technical capability. No vendor performance issues identified. Startup is DPIIT verified.", "linked_task": None, "linked_dependency": None, "data_class": DATA_CLASS},
    ],
    # ── NEW: Decision Replay ───────────────────────────────────────────────────
    "decision_replay": {
        "id": "replay-1042",
        "problem": "AI Road Damage Detection for Public Transport Routes",
        "problem_id": "1042",
        "decision_date": "2026-10-12",
        "model_version": "PRAMAN-Rank-v2.1",
        "dataset_version": "Procurement-Outcomes-2026-Q3",
        "evidence_records_used": 34,
        "criteria": [
            {"name": "Requirement Match", "weight_pct": 30},
            {"name": "Evidence Strength", "weight_pct": 25},
            {"name": "Pilot Performance", "weight_pct": 20},
            {"name": "Implementation Risk", "weight_pct": 15},
            {"name": "Cost Alignment", "weight_pct": 10},
        ],
        "startup_scores": [
            {"startup": "SkylineAI Solutions", "score": 92.7, "rank": 1},
            {"startup": "AeroScan Tech", "score": 87.4, "rank": 2},
            {"startup": "UrbanSentry", "score": 81.9, "rank": 3},
        ],
        "human_override": False,
        "final_decision": "SkylineAI Solutions selected — Proceed to Procurement Review",
        "officer": "Ananya Deshmukh",
        "data_class": DATA_CLASS,
    },
    # ── NEW: Model Versions ────────────────────────────────────────────────────
    "model_versions": [
        {
            "id": "mv-001",
            "model_name": "PRAMAN-Rank",
            "version": "v2.1",
            "dataset_name": "Procurement-Outcomes",
            "dataset_version": "2026-Q3",
            "ranking_policy": "Ranking Policy v3",
            "deployed_on": "2026-09-15",
            "training_data_description": "Historical procurement outcomes from 47 government innovation pilots across Maharashtra, 2022–2026. Includes pilot scores, implementation timelines, actual KPI outcomes, and failure analysis from 12 failed implementations.",
            "outcomes_included": 47,
            "data_class": DATA_CLASS,
        },
        {
            "id": "mv-002",
            "model_name": "PRAMAN-Rank",
            "version": "v1.4",
            "dataset_name": "Procurement-Outcomes",
            "dataset_version": "2025-Q4",
            "ranking_policy": "Ranking Policy v2",
            "deployed_on": "2025-12-01",
            "training_data_description": "Historical procurement outcomes from 29 government innovation pilots across Maharashtra, 2022–2025. Earlier version without implementation risk dimension.",
            "outcomes_included": 29,
            "data_class": DATA_CLASS,
        },
    ],
}


STATE = deepcopy(BASE_STATE)


def audit(action: str, entity: str, actor: str = "Ananya Deshmukh", role: str = "officer", reason: str = "Demo workflow action") -> dict:
    event = {
        "id": str(uuid4()),
        "timestamp": now(),
        "actor": actor,
        "role": role,
        "action": action,
        "entity": entity,
        "reason": reason,
        "system_version": "praman-deterministic-v1",
        "data_class": DATA_CLASS,
    }
    STATE["audit"].append(event)
    return event


def reset_state() -> dict:
    STATE.clear()
    STATE.update(deepcopy(BASE_STATE))
    audit("Problem Created", "Problem #1042", reason="Hero demo reset loaded simulated problem")
    return STATE
